# Generated by Django 3.1.1 on 2020-11-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr',
            field=models.IntegerField(max_length=264, unique=True),
        ),
    ]
