# Generated by Django 3.1.1 on 2020-11-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201119_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr',
            field=models.IntegerField(unique=True),
        ),
    ]
